In [15]:
import math, time, statistics, random
import numpy as np
from utils import Task
from compute.aug_server import ShareCompServer  # vehicle server

In [18]:
x = np.zeros((10,3))
print(x)
print(x[3,:])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [45]:
np.random.rand(1)[0]

0.504073338110091

In [38]:
a = list(range(20))
print(a[0:10])
print(a[10:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [35]:
allocation = []
allocation.append(1)
allocation.append([3])
allocation.append([1,2])
print(allocation)

[1, [3], [1, 2]]


In [23]:
def count_reapting(data):
    data_count = np.zeros_like(data)
    for i in range(len(data)):
        for j in np.unique(data):
            # print(np.sum(data==j))
            if data[i] == j:
                data_count[i] = np.sum(data==j)
    return data_count

In [31]:
data = np.array([0,1,2,3,4,5,6,7,8,8,8, 9 ,9])
data_sort = np.sort(data)[::-1]
print(data_sort)
print(np.argsort(data)[::-1])

[9 9 8 8 8 7 6 5 4 3 2 1 0]
[12 11 10  9  8  7  6  5  4  3  2  1  0]


In [140]:
lambda_prob = 0.0001

time_length = 3500

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)


time_length = 5000

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)

success prob: 0.7046880897187134, when time latency is 3500
fail prob: 0.29531191028128656, when time latency is 3500
0.08720912435398265
success prob: 0.6065306597126334, when time latency is 5000
fail prob: 0.3934693402873666, when time latency is 5000
0.15481812174617549


In [145]:
lambda_prob = 0.00005

time_length = 5000

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)


time_length = 5000

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)

success prob: 0.7788007830714049, when time latency is 5000
fail prob: 0.22119921692859512, when time latency is 5000
0.04892909356982368
success prob: 0.7788007830714049, when time latency is 5000
fail prob: 0.22119921692859512, when time latency is 5000
0.04892909356982368


In [47]:
a = [0,1,0,1,0,1,0,1,0,1]
b = [x+1 for x, y in list(enumerate(a)) if y == 1]
print(b)

[2, 4, 6, 8, 10]


In [139]:
UniqueCarrier = "CA"
Origin = "111"
name = "-".join([UniqueCarrier, Origin])
time = 100
results = [name, str(time)]
print("\t".join(results))

CA-111	100


In [75]:
N = 100
D = 20
x = np.random.randint(0, 2, [N, D ])
print(np.shape(x))


b = np.eye(D)
c = np.eye(D) + np.eye(D, k=1)
c[D-1, 0] = 1

a = np.vstack((b,c))
print(np.shape(a))
# print(a)


(100, 20)
(40, 20)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [87]:
xx = np.empty(shape = (0,20))
for i in range(100):
    index = np.random.randint(100)
    # print(index)
    xx = np.vstack((xx,x[index, :] ))
print(np.shape(xx))
print(xx)

(100, 20)
[[1. 0. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [1. 1. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 1. 1.]]


In [89]:
np.shape(np.zeros([N, D ]))

(100, 20)

In [137]:
N =200
vehicles_num = 20
tasks_num = 1
D = tasks_num * vehicles_num

# PSO main part
# random sample to initialize partocles
ones = np.eye(vehicles_num)
twos = np.eye(vehicles_num) + np.eye(vehicles_num, k=1) + np.eye(vehicles_num, k=1-vehicles_num)
sample = np.vstack((ones, twos))

x = np.zeros([N, D ])

for i in range(tasks_num):
    
    for j in range(N):
        index = np.random.randint(np.shape(sample)[0])
        x[j,i* vehicles_num : (i+1)*vehicles_num] = sample[index, :]
print(x[10,:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [35]:
np.random.randint(0, 20, [10, 5])

array([[14,  8, 15,  5,  6],
       [ 8,  7, 10, 12,  9],
       [ 8,  1, 10,  7,  1],
       [15,  5, 17, 19,  5],
       [ 0,  4, 15,  5, 17],
       [ 7, 18, 14,  7, 12],
       [18, 18,  2, 12, 15],
       [ 1, 16, 11,  7, 15],
       [11, 15,  7, 12, 14],
       [17,  1, 18,  5, 16]])

In [42]:
a = list(range(10))
b = list(range(10,20))
for i, j in enumerate(a,b):
    print(a,b)

TypeError: 'list' object cannot be interpreted as an integer

In [24]:
x = np.random.randint(0, 2, [10, 1])+1

print(x[2,0])
print(x)

2
[[2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]]


In [20]:
random.uniform(-10, 10)

7.678365115572184

In [10]:
tasks = [Task(tid=1+k, curr_time=0, generated_vid = 0) for k in range(10)]
print(len(tasks))
remove_list = []

for tk in tasks:
    if tk.generated_vid==0:
        print("yes", tk.tid)
        remove_list.append(tk)

# for tk in remove_list:
#     tasks.remove(tk)

print(tasks, len(tasks))

10
yes 1
yes 2
yes 3
yes 4
yes 5
yes 6
yes 7
yes 8
yes 9
yes 10
[<utils.Task object at 0x115ccf290>, <utils.Task object at 0x11580f170>, <utils.Task object at 0x115d1f5f0>, <utils.Task object at 0x115d1f860>, <utils.Task object at 0x115d1fef0>, <utils.Task object at 0x115d1d700>, <utils.Task object at 0x115d1fad0>, <utils.Task object at 0x115d1ff20>, <utils.Task object at 0x115d1ffb0>, <utils.Task object at 0x115d1fda0>] 10


In [20]:
tasks = [Task(tid=k, curr_time=0, generated_vid = 0) for k in range(10)]
print('task number:',len(tasks))

for tk in tasks:
    print(tk.tid)
    tasks.remove(tk)
    # print(tk.tid)
print('task number:',len(tasks))

task number: 10
0
2
4
6
8
task number: 5


In [22]:
a = 10

if a > 1:
    print('1')
elif a >2:
    print('2')
else:
    print('3')

1


In [5]:
Vehicles = []
for vid in range(30):
            Vehicles.append(ShareCompServer(vid, capacity=10))
print(Vehicles[0].vid)

0


In [15]:
a = list(range(10))
b = ['1']

start_time = time.time()
a.remove(9)
useage_time = time.time()-start_time

start_time = time.time()
try:
    a.remove(9)
except:
    pass
tryuseage_time = time.time()-start_time
print(a, useage_time, tryuseage_time)
if b:
    print(1)
else:
    print(2)

[0, 1, 2, 3, 4, 5, 6, 7, 8] 3.409385681152344e-05 3.814697265625e-05
1


In [59]:
l = 0.5
n = 0
cdf = 0
cdf_list = []

while 1:
    # print(n)
    # prob = l**n*math.exp(-l)/math.factorial(n)
    prob = l**n/math.factorial(n)*math.exp(-l)
    cdf += prob
    cdf_list.append(cdf)
    # print(prob)
    # print(l**n*math.exp(l)/math.factorial(n))
    if cdf >= 1 or (n > l and prob<=1e-16):
        break
    n+=1

print(n)
print(cdf_list)
print(len(cdf_list))

14
[0.6065306597126334, 0.9097959895689501, 0.9856123220330293, 0.9982483774437092, 0.9998278843700442, 0.9999858350626777, 0.9999989976203971, 0.9999999378030914, 0.9999999965645098, 0.999999999829033, 0.9999999999922592, 0.9999999999996786, 0.9999999999999877, 0.9999999999999996, 1.0]
15


In [181]:
target = 0.9

left, right = 0, len(cdf_list) - 1
while left < right:
    mid = left + (right - left) // 2
    if cdf_list[mid] < target:
        left = mid + 1
    elif cdf_list[mid] > target:
        right = mid - 1

mid = left + (right - left) // 2

if cdf_list[mid] < target and target <= cdf_list[mid+1]:
    mid+=1
elif cdf_list[mid+1] < target:
    mid+=2

print('result:',mid, left, right)

7 0 6
3 0 2
1 2 2
result: 1 2 2
result: 2 2 2


In [8]:
a = 1
b=2
print('ok %s okok %sok' %(a,b))

ok 1 okok 2ok


In [7]:
statistics.mean([1,2])

1.5