In [9]:
import math, time, statistics, random
import numpy as np
# from utils import Task
# from compute.aug_server import ShareCompServer  # vehicle server

In [6]:
a = [3.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 3.0, 3.0, 1.0, 3.0, 2.0, 2.0, 2.0, 3.0, 0.0, 2.0, 1.0, 3.0, 3.0, 1.0, 1.0]
print(sum(a))
print(sum(a)/len(a))


80.0
1.8604651162790697


In [18]:
x = np.zeros((10,3))
print(x)
print(x[3,:])



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [45]:
np.random.rand(1)[0]

0.504073338110091

In [62]:
random.randint(1, 20)

3

In [38]:
a = list(range(20))
print(a[0:10])
print(a[10:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [35]:
allocation = []
allocation.append(1)
allocation.append([3])
allocation.append([1,2])
print(allocation)

[1, [3], [1, 2]]


In [23]:
def count_reapting(data):
    data_count = np.zeros_like(data)
    for i in range(len(data)):
        for j in np.unique(data):
            # print(np.sum(data==j))
            if data[i] == j:
                data_count[i] = np.sum(data==j)
    return data_count

In [13]:
data = np.array([0, -10 ,1,2,3,4,5,6,7,8,8,8, 9 ,9])
data_sort = np.sort(data)[::-1]
print(data_sort)
print(np.argsort(data)[0])

[  9   9   8   8   8   7   6   5   4   3   2   1   0 -10]
1


In [140]:
lambda_prob = 0.0001

time_length = 3500

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)


time_length = 5000

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)

success prob: 0.7046880897187134, when time latency is 3500
fail prob: 0.29531191028128656, when time latency is 3500
0.08720912435398265
success prob: 0.6065306597126334, when time latency is 5000
fail prob: 0.3934693402873666, when time latency is 5000
0.15481812174617549


In [145]:
lambda_prob = 0.0005

time_length = 100

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)


time_length = 5000

prob = math.exp(- time_length * lambda_prob)
print("success prob: {}, when time latency is {}".format(prob,time_length))
print("fail prob: {}, when time latency is {}".format(1-prob,time_length))
print((1-prob)**2)

success prob: 0.951229424500714, when time latency is 100
fail prob: 0.048770575499285984, when time latency is 100
0.0023785690345315543
success prob: 0.0820849986238988, when time latency is 5000
fail prob: 0.9179150013761012, when time latency is 5000
0.8425679497512878


In [47]:
a = [0,1,0,1,0,1,0,1,0,1]
b = [x+1 for x, y in list(enumerate(a)) if y == 1]
print(b)

[2, 4, 6, 8, 10]


In [139]:
UniqueCarrier = "CA"
Origin = "111"
name = "-".join([UniqueCarrier, Origin])
time = 100
results = [name, str(time)]
print("\t".join(results))

CA-111	100


In [75]:
N = 100
D = 20
x = np.random.randint(0, 2, [N, D ])
print(np.shape(x))


b = np.eye(D)
c = np.eye(D) + np.eye(D, k=1)
c[D-1, 0] = 1

a = np.vstack((b,c))
print(np.shape(a))
# print(a)


(100, 20)
(40, 20)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [87]:
xx = np.empty(shape = (0,20))
for i in range(100):
    index = np.random.randint(100)
    # print(index)
    xx = np.vstack((xx,x[index, :] ))
print(np.shape(xx))
print(xx)

(100, 20)
[[1. 0. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [1. 1. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 1. 1.]]


In [89]:
np.shape(np.zeros([N, D ]))

(100, 20)

In [137]:
N =200
vehicles_num = 20
tasks_num = 1
D = tasks_num * vehicles_num

# PSO main part
# random sample to initialize partocles
ones = np.eye(vehicles_num)
twos = np.eye(vehicles_num) + np.eye(vehicles_num, k=1) + np.eye(vehicles_num, k=1-vehicles_num)
sample = np.vstack((ones, twos))

x = np.zeros([N, D ])

for i in range(tasks_num):
    
    for j in range(N):
        index = np.random.randint(np.shape(sample)[0])
        x[j,i* vehicles_num : (i+1)*vehicles_num] = sample[index, :]
print(x[10,:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [35]:
np.random.randint(0, 20, [10, 5])

array([[14,  8, 15,  5,  6],
       [ 8,  7, 10, 12,  9],
       [ 8,  1, 10,  7,  1],
       [15,  5, 17, 19,  5],
       [ 0,  4, 15,  5, 17],
       [ 7, 18, 14,  7, 12],
       [18, 18,  2, 12, 15],
       [ 1, 16, 11,  7, 15],
       [11, 15,  7, 12, 14],
       [17,  1, 18,  5, 16]])

In [42]:
a = list(range(10))
b = list(range(10,20))
for i, j in enumerate(a,b):
    print(a,b)

TypeError: 'list' object cannot be interpreted as an integer

In [24]:
x = np.random.randint(0, 2, [10, 1])+1

print(x[2,0])
print(x)

2
[[2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]]


In [70]:
import itertools

a = list(range(20))

b =itertools.combinations(a,2)
for v in b:
    print(v)

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)
(0, 8)
(0, 9)
(0, 10)
(0, 11)
(0, 12)
(0, 13)
(0, 14)
(0, 15)
(0, 16)
(0, 17)
(0, 18)
(0, 19)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)
(1, 9)
(1, 10)
(1, 11)
(1, 12)
(1, 13)
(1, 14)
(1, 15)
(1, 16)
(1, 17)
(1, 18)
(1, 19)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(2, 10)
(2, 11)
(2, 12)
(2, 13)
(2, 14)
(2, 15)
(2, 16)
(2, 17)
(2, 18)
(2, 19)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(3, 9)
(3, 10)
(3, 11)
(3, 12)
(3, 13)
(3, 14)
(3, 15)
(3, 16)
(3, 17)
(3, 18)
(3, 19)
(4, 5)
(4, 6)
(4, 7)
(4, 8)
(4, 9)
(4, 10)
(4, 11)
(4, 12)
(4, 13)
(4, 14)
(4, 15)
(4, 16)
(4, 17)
(4, 18)
(4, 19)
(5, 6)
(5, 7)
(5, 8)
(5, 9)
(5, 10)
(5, 11)
(5, 12)
(5, 13)
(5, 14)
(5, 15)
(5, 16)
(5, 17)
(5, 18)
(5, 19)
(6, 7)
(6, 8)
(6, 9)
(6, 10)
(6, 11)
(6, 12)
(6, 13)
(6, 14)
(6, 15)
(6, 16)
(6, 17)
(6, 18)
(6, 19)
(7, 8)
(7, 9)
(7, 10)
(7, 11)
(7, 12)
(7, 13)
(7, 14)
(7, 15)
(7, 16)
(7, 17)
(7, 18)
(7, 19)
(8, 9)
(8, 10)
(8, 11)
(8, 12)
(8, 13)
(8, 14)
(8, 1

In [109]:
vehicles_num = 20 # 20 by default
tasks_num = 2
allocation_space = []
for allocated_v_num in range(1,4):
    sample_list = itertools.combinations(list(range(vehicles_num)),allocated_v_num)
    for sample_item in sample_list:
        particle = [0] * vehicles_num
        for j in sample_item:
            particle[j] = 1
        allocation_space.append(particle)

allocation_num = len(allocation_space)
x=[]
for _ in range(100):
    particle_temp = []
    for _ in range(tasks_num):
        particle_temp.extend(allocation_space[np.random.randint(allocation_num)])
    x.append(particle_temp)
print(np.shape(x))

(100, 40)

In [10]:
tasks = [Task(tid=1+k, curr_time=0, generated_vid = 0) for k in range(10)]
print(len(tasks))
remove_list = []

for tk in tasks:
    if tk.generated_vid==0:
        print("yes", tk.tid)
        remove_list.append(tk)

# for tk in remove_list:
#     tasks.remove(tk)

print(tasks, len(tasks))

10
yes 1
yes 2
yes 3
yes 4
yes 5
yes 6
yes 7
yes 8
yes 9
yes 10
[<utils.Task object at 0x115ccf290>, <utils.Task object at 0x11580f170>, <utils.Task object at 0x115d1f5f0>, <utils.Task object at 0x115d1f860>, <utils.Task object at 0x115d1fef0>, <utils.Task object at 0x115d1d700>, <utils.Task object at 0x115d1fad0>, <utils.Task object at 0x115d1ff20>, <utils.Task object at 0x115d1ffb0>, <utils.Task object at 0x115d1fda0>] 10


In [20]:
tasks = [Task(tid=k, curr_time=0, generated_vid = 0) for k in range(10)]
print('task number:',len(tasks))

for tk in tasks:
    print(tk.tid)
    tasks.remove(tk)
    # print(tk.tid)
print('task number:',len(tasks))

task number: 10
0
2
4
6
8
task number: 5


In [22]:
a = 10

if a > 1:
    print('1')
elif a >2:
    print('2')
else:
    print('3')

1


In [5]:
Vehicles = []
for vid in range(30):
            Vehicles.append(ShareCompServer(vid, capacity=10))
print(Vehicles[0].vid)

0


In [15]:
a = list(range(10))
b = ['1']

start_time = time.time()
a.remove(9)
useage_time = time.time()-start_time

start_time = time.time()
try:
    a.remove(9)
except:
    pass
tryuseage_time = time.time()-start_time
print(a, useage_time, tryuseage_time)
if b:
    print(1)
else:
    print(2)

[0, 1, 2, 3, 4, 5, 6, 7, 8] 3.409385681152344e-05 3.814697265625e-05
1


In [59]:
l = 0.5
n = 0
cdf = 0
cdf_list = []

while 1:
    # print(n)
    # prob = l**n*math.exp(-l)/math.factorial(n)
    prob = l**n/math.factorial(n)*math.exp(-l)
    cdf += prob
    cdf_list.append(cdf)
    # print(prob)
    # print(l**n*math.exp(l)/math.factorial(n))
    if cdf >= 1 or (n > l and prob<=1e-16):
        break
    n+=1

print(n)
print(cdf_list)
print(len(cdf_list))

14
[0.6065306597126334, 0.9097959895689501, 0.9856123220330293, 0.9982483774437092, 0.9998278843700442, 0.9999858350626777, 0.9999989976203971, 0.9999999378030914, 0.9999999965645098, 0.999999999829033, 0.9999999999922592, 0.9999999999996786, 0.9999999999999877, 0.9999999999999996, 1.0]
15


In [181]:
target = 0.9

left, right = 0, len(cdf_list) - 1
while left < right:
    mid = left + (right - left) // 2
    if cdf_list[mid] < target:
        left = mid + 1
    elif cdf_list[mid] > target:
        right = mid - 1

mid = left + (right - left) // 2

if cdf_list[mid] < target and target <= cdf_list[mid+1]:
    mid+=1
elif cdf_list[mid+1] < target:
    mid+=2

print('result:',mid, left, right)

7 0 6
3 0 2
1 2 2
result: 1 2 2
result: 2 2 2


In [8]:
a = 1
b=2
print('ok %s okok %sok' %(a,b))

ok 1 okok 2ok


In [138]:
if np.random.randint(2):
    print('1')

1


In [48]:
import itertools
import numpy as np
vehicles_num = 20# 20 by default
tasks_num = 2
D = tasks_num * vehicles_num
N = 100
# PSO main part
# random sample to initialize partocles
# x = np.random.randint(0, 2, [N, D ]) # 0-20 represent vehicle_id
allocation_space = []
for allocated_v_num in range(1, 3):
    sample_list = itertools.combinations(list(range(vehicles_num)),allocated_v_num)
    for sample_item in sample_list:
        particle = [0] * vehicles_num
        for j in sample_item:
            particle[j] = 1
        allocation_space.append(particle)

print(len(allocation_space))
# print(allocation_space[:20])
x=[]
for i in range(vehicles_num):
    particle_temp = []
    index_list = list(range(vehicles_num))
    for j in range(tasks_num):
        # sample_allcation = allocation_space[np.random.randint(vehicles_num)]
        if j != 0:
            index = random.sample(index_list, 1)[0]
        else:
            index = i
        index_list.remove(index)
        particle_temp.extend(allocation_space[index])
    x.append(particle_temp)
    
for _ in range(N-vehicles_num):
    particle_temp = []
    for _ in range(tasks_num):
        # sample_allcation = allocation_space[np.random.randint(vehicles_num)]
        particle_temp.extend(allocation_space[np.random.randint(len(allocation_space))])
    x.append(particle_temp)
x = np.array(x)
print(x[:20])

210
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [44]:
index_list = list(range(vehicles_num))
b = 16
print(type(16))
c = index = random.sample(index_list, 1)[0]
print(c, type(c))
index_list.remove(b)
print(index_list)
index_list.remove(c)
print(index_list)

<class 'int'>
6 <class 'int'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19]


In [49]:
for i in range(1,3):
    print(i)

1
2


In [50]:
n = 3
m = 2
math.factorial(n)//(math.factorial(n-m)*math.factorial(m))

3

In [181]:
np.random.normal(0, 8)

-12.156840504670045

In [239]:
a = np.random.rand(1)*2*math.pi
d = np.random.randint(30, 500, 1)[0]
cos_dis = math.cos(a)*d
sin_dis = math.sin(a)*d

print(cos_dis,sin_dis)

-61.83603894196726 -114.35166937114434


/var/folders/4y/6hwhj6cx083_rlnxjx67lthm0000gn/T/ipykernel_85932/1807837439.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  cos_dis = math.cos(a)*d
/var/folders/4y/6hwhj6cx083_rlnxjx67lthm0000gn/T/ipykernel_85932/1807837439.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sin_dis = math.sin(a)*d


In [241]:
np.round([cos_dis, sin_dis])

array([ -62., -114.])

In [236]:
[0.5, 0.3]*2

[0.5, 0.3, 0.5, 0.3]